const baseObjects = [
  { id: 'sun', fa: 'خورشید', en: 'Sun', type: 'ستاره', order: 0, diameter: 1392700, distance: 0, year: '—', day: '۲۵ تا ۳۵ روز', moons: 0, gravity: '۲۷۴ m/s²', temp: '۵٬۵۰۰°C سطح', color: 'linear-gradient(135deg,#fff7a5,#ff9e18,#ff5a00)', radius: 3.9, orbit: 0, spin: .08, texture: null, summary: 'ستاره مرکزی منظومه؛ بیش از ۹۹٫۸٪ جرم کل منظومه را در خود دارد و منبع نور، گرما و باد خورشیدی است.', note: 'فعالیت مغناطیسی خورشید آب‌وهوای فضایی، شفق و طوفان ژئومغناطیسی می‌سازد.' },
  { id: 'mercury', fa: 'عطارد', en: 'Mercury', type: 'سیاره', order: 1, diameter: 4879, distance: 57.9, year: '۸۸ روز', day: '۵۸٫۶ روز', moons: 0, gravity: '۳٫۷ m/s²', temp: '−۱۸۰ تا ۴۳۰°C', color: 'linear-gradient(135deg,#d7d1c6,#8d929d)', radius: .28, orbit: 6, spin: .6, texture: '2k_mercury.jpg', summary: 'نزدیک‌ترین سیاره به خورشید؛ کوچک، سنگی و تقریباً بی‌جو با دهانه‌های برخوردی فراوان.', note: 'در دهانه‌های قطبی سایه‌دار عطارد یخ آب شناسایی شده است.' },
  { id: 'venus', fa: 'زهره', en: 'Venus', type: 'سیاره', order: 2, diameter: 12104, distance: 108.2, year: '۲۲۵ روز', day: '۲۴۳ روز', moons: 0, gravity: '۸٫۹ m/s²', temp: '۴۶۵°C', color: 'linear-gradient(135deg,#fff1b6,#d89032)', radius: .58, orbit: 8.2, spin: -.22, texture: '2k_venus_surface.jpg', summary: 'هم‌اندازه زمین اما با جو بسیار چگال دی‌اکسیدکربن و گرم‌ترین سطح سیاره‌ای منظومه.', note: 'چرخش زهره کند و وارونه است؛ شبانه‌روز آن از سالش طولانی‌تر است.' },
  { id: 'earth', fa: 'زمین', en: 'Earth', type: 'سیاره', order: 3, diameter: 12742, distance: 149.6, year: '۳۶۵٫۲۵ روز', day: '۲۳٫۹ ساعت', moons: 1, gravity: '۹٫۸ m/s²', temp: 'میانگین ۱۵°C', color: 'radial-gradient(circle at 35% 30%,#78dd72,#2772ff 45%,#123d9a)', radius: .64, orbit: 10.8, spin: 1, texture: '2k_earth_daymap.jpg', summary: 'تنها جهان شناخته‌شده با حیات، آب مایع پایدار سطحی و جو نیتروژن-اکسیژن.', note: 'میدان مغناطیسی و جو زمین سپری حیاتی در برابر باد خورشیدی و پرتوهای پرانرژی هستند.' },
  { id: 'moon', fa: 'ماه', en: 'Moon', type: 'قمر', order: 3.1, diameter: 3475, distance: 149.6, year: '۲۷٫۳ روز دور زمین', day: '۲۹٫۵ روز قمری', moons: 0, gravity: '۱٫۶۲ m/s²', temp: '−۱۷۳ تا ۱۲۷°C', color: 'linear-gradient(135deg,#f5f6fb,#9da6bd)', radius: .18, orbit: 11.65, parent: 'earth', spin: .9, texture: '2k_moon.jpg', summary: 'قمر طبیعی زمین؛ عامل اصلی جزرومدها و پایدارکننده کجی محور زمین.', note: 'ماه احتمالاً از برخورد جرمی هم‌اندازه مریخ با زمین جوان پدید آمده است.' },
  { id: 'mars', fa: 'مریخ', en: 'Mars', type: 'سیاره', order: 4, diameter: 6779, distance: 227.9, year: '۶۸۷ روز', day: '۲۴٫۶ ساعت', moons: 2, gravity: '۳٫۷۱ m/s²', temp: 'میانگین −۶۵°C', color: 'linear-gradient(135deg,#ff9b6b,#c63e2a)', radius: .38, orbit: 13.6, spin: .97, texture: '2k_mars.jpg', summary: 'سیاره سرخ با آتشفشان المپوس، دره‌های عظیم، کلاهک‌های یخی و نشانه‌های آب باستانی.', note: 'فوبوس و دیموس دو قمر کوچک و نامنظم مریخ هستند.' },
  { id: 'asteroids', fa: 'کمربند سیارکی', en: 'Asteroid Belt', type: 'ناحیه', order: 4.5, diameter: 0, distance: 329, year: '۳ تا ۶ سال', day: 'متغیر', moons: '۱۵۰+ سیارک قمر دارند', gravity: 'بسیار کم', temp: 'سرد و متغیر', color: 'linear-gradient(135deg,#b9a48d,#5d6478)', radius: 0, orbit: 16.5, summary: 'منطقه‌ای میان مریخ و مشتری با بقایای سنگی و فلزی آغاز منظومه.', note: 'سرس، وستا، پالاس و هیجیا از بزرگ‌ترین اجرام این کمربند هستند.' },
  { id: 'ceres', fa: 'سرس', en: 'Ceres', type: 'سیاره کوتوله', order: 4.6, diameter: 940, distance: 413.7, year: '۴٫۶ سال', day: '۹٫۱ ساعت', moons: 0, gravity: '۰٫۲۸ m/s²', temp: 'حدود −۱۰۵°C', color: 'linear-gradient(135deg,#d8d4ca,#767c88)', radius: .2, orbit: 16.7, spin: 1.4, texture: '2k_ceres_fictional.jpg', summary: 'بزرگ‌ترین جرم کمربند سیارکی و تنها سیاره کوتوله در ناحیه درونی منظومه.', note: 'داده‌های Dawn از یخ، نمک و احتمال اقیانوس باستانی در سرس پشتیبانی می‌کند.' },
  { id: 'jupiter', fa: 'مشتری', en: 'Jupiter', type: 'سیاره', order: 5, diameter: 139820, distance: 778.6, year: '۱۱٫۹ سال', day: '۹٫۹ ساعت', moons: 101, gravity: '۲۴٫۸ m/s²', temp: 'ابرها −۱۱۰°C', color: 'repeating-linear-gradient(0deg,#d28b4b 0 10px,#fff0d8 10px 22px,#a95f42 22px 30px)', radius: 1.55, orbit: 20.2, spin: 2.3, texture: '2k_jupiter.jpg', summary: 'بزرگ‌ترین سیاره، غول گازی با لکه سرخ بزرگ، میدان مغناطیسی عظیم و قمرهای گالیله‌ای.', note: 'آیو، اروپا، گانیمد و کالیستو چهار قمر بزرگ آن‌اند؛ گانیمد بزرگ‌ترین قمر منظومه است.' },
  { id: 'saturn', fa: 'زحل', en: 'Saturn', type: 'سیاره', order: 6, diameter: 116460, distance: 1433.5, year: '۲۹٫۵ سال', day: '۱۰٫۷ ساعت', moons: 274, gravity: '۱۰٫۴ m/s²', temp: 'ابرها −۱۴۰°C', color: 'linear-gradient(135deg,#fff0c7,#d79b60)', radius: 1.3, orbit: 25.2, spin: 2, texture: '2k_saturn.jpg', summary: 'غول گازی کم‌چگال با باشکوه‌ترین سامانه حلقه‌ای و قمرهای مهمی مثل تیتان و انسلادوس.', note: 'تیتان جو چگال و دریاچه‌های متان دارد؛ انسلادوس فواره‌های یخی و اقیانوس زیرسطحی نشان می‌دهد.' },
  { id: 'uranus', fa: 'اورانوس', en: 'Uranus', type: 'سیاره', order: 7, diameter: 50724, distance: 2872.5, year: '۸۴ سال', day: '۱۷٫۲ ساعت', moons: 28, gravity: '۸٫۷ m/s²', temp: 'ابرها −۱۹۵°C', color: 'linear-gradient(135deg,#b8fff8,#4fc8e9)', radius: .9, orbit: 30, spin: 1.4, texture: '2k_uranus.jpg', summary: 'غول یخی آبی-سبز با محور چرخش بسیار کج؛ گویی به پهلو دور خورشید می‌گردد.', note: 'متان جو اورانوس نور سرخ را جذب می‌کند و رنگ فیروزه‌ای می‌سازد.' },
  { id: 'neptune', fa: 'نپتون', en: 'Neptune', type: 'سیاره', order: 8, diameter: 49244, distance: 4495.1, year: '۱۶۴٫۸ سال', day: '۱۶٫۱ ساعت', moons: 16, gravity: '۱۱٫۱۵ m/s²', temp: 'ابرها −۲۰۰°C', color: 'linear-gradient(135deg,#6ea1ff,#173ec2)', radius: .88, orbit: 34.5, spin: 1.5, texture: '2k_neptune.jpg', summary: 'دورترین سیاره رسمی، غول یخی با بادهای بسیار سریع و قمر بزرگ تریتون.', note: 'تریتون احتمالاً جرمی اسیرشده از کمربند کویپر است و مدار وارونه دارد.' },
  { id: 'kuiper', fa: 'کمربند کویپر', en: 'Kuiper Belt', type: 'ناحیه', order: 8.5, diameter: 0, distance: 5900, year: 'دهه‌ها تا صدها سال', day: 'متغیر', moons: 'بسیاری از اجرام', gravity: 'بسیار کم', temp: 'بسیار سرد', color: 'linear-gradient(135deg,#b7d7ff,#596baf)', radius: 0, orbit: 38, summary: 'حلقه‌ای پهناور از اجرام یخی فراتر از نپتون؛ مخزن پلوتو و بسیاری از دنباله‌دارهای کوتاه‌دوره.', note: 'این ناحیه از حدود ۳۰ تا ۵۰ واحد نجومی از خورشید گسترده است.' },
  { id: 'pluto', fa: 'پلوتو', en: 'Pluto', type: 'سیاره کوتوله', order: 9, diameter: 2377, distance: 5906.4, year: '۲۴۸ سال', day: '۶٫۴ روز', moons: 5, gravity: '۰٫۶۲ m/s²', temp: 'حدود −۲۳۰°C', color: 'linear-gradient(135deg,#ffe0be,#8d6c62)', radius: .24, orbit: 38.8, spin: .8, texture: '2k_pluto.jpg', summary: 'دنیای یخی کمربند کویپر با قلب روشن تومبا رِجیو و قمر بزرگ شارون.', note: 'پلوتو و شارون مانند سامانه‌ای دوتایی پیرامون نقطه‌ای بیرون از پلوتو می‌چرخند.' },
  { id: 'haumea', fa: 'هائومیا', en: 'Haumea', type: 'سیاره کوتوله', order: 10, diameter: 1632, distance: 6450, year: '۲۸۵ سال', day: '۳٫۹ ساعت', moons: 2, gravity: 'کم', temp: 'حدود −۲۴۰°C', color: 'linear-gradient(135deg,#ffffff,#9fb6d4)', radius: .24, orbit: 40.5, spin: 2.5, summary: 'جرمی کشیده و بسیار تندچرخ در کمربند کویپر با حلقه باریک و دو قمر.', note: 'چرخش سریع، شکل هائومیا را از کره کامل دور کرده است.' },
  { id: 'makemake', fa: 'ماکی‌ماکی', en: 'Makemake', type: 'سیاره کوتوله', order: 11, diameter: 1430, distance: 6847, year: '۳۰۶ سال', day: '۲۲٫۸ ساعت', moons: 1, gravity: 'کم', temp: 'حدود −۲۴۰°C', color: 'linear-gradient(135deg,#d59b75,#7d4534)', radius: .22, orbit: 42.6, spin: 1, summary: 'یکی از بزرگ‌ترین اجرام کمربند کویپر، پوشیده از یخ‌های متان و اتان.', note: 'قمر کوچک آن در سال ۲۰۱۶ با رصدهای هابل گزارش شد.' },
  { id: 'eris', fa: 'اریس', en: 'Eris', type: 'سیاره کوتوله', order: 12, diameter: 2326, distance: 10120, year: '۵۵۷ سال', day: '۲۵٫۹ ساعت', moons: 1, gravity: '۰٫۸۲ m/s²', temp: 'حدود −۲۴۳°C', color: 'linear-gradient(135deg,#f7f8ff,#b9bfd2)', radius: .25, orbit: 46, spin: .9, summary: 'سیاره کوتوله بسیار دور و پرجرم که کشف آن به بازتعریف واژه سیاره کمک کرد.', note: 'قمر اریس «دیسنومیا» نام دارد.' },
  { id: 'comets', fa: 'دنباله‌دارها', en: 'Comets', type: 'جرم کوچک', order: 13, diameter: 10, distance: 0, year: 'چند سال تا هزاران سال', day: 'متغیر', moons: 0, gravity: 'ناچیز', temp: 'بسته به نزدیکی به خورشید', color: 'linear-gradient(135deg,#e9fbff,#74a9ff)', radius: .15, orbit: 48, summary: 'گلوله‌های یخ، غبار و سنگ که با نزدیک شدن به خورشید گیسو و دم نورانی می‌سازند.', note: 'هالی، 67P و هیل-باپ نمونه‌های شناخته‌شده‌اند؛ منشأ بسیاری از آن‌ها کمربند کویپر یا ابر اورت است.' },
  { id: 'oort', fa: 'ابر اورت', en: 'Oort Cloud', type: 'ناحیه', order: 14, diameter: 0, distance: 750000, year: 'میلیون‌ها سال', day: 'نامشخص', moons: 'نامشخص', gravity: 'بسیار کم', temp: 'نزدیک صفر مطلق', color: 'linear-gradient(135deg,#eef7ff,#7d8eb9)', radius: 0, orbit: 52, summary: 'پوسته فرضی و بسیار دور از اجرام یخی پیرامون منظومه؛ سرچشمه احتمالی دنباله‌دارهای بلنددوره.', note: 'ابر اورت مستقیم تصویربرداری نشده، اما رفتار دنباله‌دارهای بلنددوره وجود آن را توضیح می‌دهد.' }
];


const orbitalElements = {
  mercury: { semiMajorAxisAu: 0.387, eccentricity: 0.2056, inclination: 7.005, longitudeOfAscendingNode: 48.331, argumentOfPeriapsis: 29.124, periodDays: 87.969, meanAnomalyAtEpoch: 174.796 },
  venus: { semiMajorAxisAu: 0.723, eccentricity: 0.0068, inclination: 3.394, longitudeOfAscendingNode: 76.680, argumentOfPeriapsis: 54.884, periodDays: 224.701, meanAnomalyAtEpoch: 50.115 },
  earth: { semiMajorAxisAu: 1, eccentricity: 0.0167, inclination: 0, longitudeOfAscendingNode: -11.260, argumentOfPeriapsis: 114.207, periodDays: 365.256, meanAnomalyAtEpoch: 358.617 },
  moon: { semiMajorAxisAu: 0.00257, eccentricity: 0.0549, inclination: 5.145, longitudeOfAscendingNode: 125.08, argumentOfPeriapsis: 318.15, periodDays: 27.322, meanAnomalyAtEpoch: 135.27, parent: 'earth' },
  mars: { semiMajorAxisAu: 1.524, eccentricity: 0.0934, inclination: 1.850, longitudeOfAscendingNode: 49.558, argumentOfPeriapsis: 286.502, periodDays: 686.980, meanAnomalyAtEpoch: 19.373 },
  ceres: { semiMajorAxisAu: 2.768, eccentricity: 0.0758, inclination: 10.59, longitudeOfAscendingNode: 80.31, argumentOfPeriapsis: 73.60, periodDays: 1680, meanAnomalyAtEpoch: 95.99 },
  jupiter: { semiMajorAxisAu: 5.203, eccentricity: 0.0489, inclination: 1.303, longitudeOfAscendingNode: 100.464, argumentOfPeriapsis: 273.867, periodDays: 4332.59, meanAnomalyAtEpoch: 20.020 },
  saturn: { semiMajorAxisAu: 9.537, eccentricity: 0.0565, inclination: 2.485, longitudeOfAscendingNode: 113.665, argumentOfPeriapsis: 339.392, periodDays: 10759.22, meanAnomalyAtEpoch: 317.020 },
  uranus: { semiMajorAxisAu: 19.191, eccentricity: 0.0472, inclination: 0.773, longitudeOfAscendingNode: 74.006, argumentOfPeriapsis: 96.998, periodDays: 30685.4, meanAnomalyAtEpoch: 142.238 },
  neptune: { semiMajorAxisAu: 30.069, eccentricity: 0.0086, inclination: 1.770, longitudeOfAscendingNode: 131.784, argumentOfPeriapsis: 276.336, periodDays: 60190, meanAnomalyAtEpoch: 256.228 },
  pluto: { semiMajorAxisAu: 39.482, eccentricity: 0.2488, inclination: 17.16, longitudeOfAscendingNode: 110.299, argumentOfPeriapsis: 113.834, periodDays: 90560, meanAnomalyAtEpoch: 14.53 },
  haumea: { semiMajorAxisAu: 43.13, eccentricity: 0.19, inclination: 28.2, longitudeOfAscendingNode: 122.2, argumentOfPeriapsis: 240, periodDays: 103774, meanAnomalyAtEpoch: 205 },
  makemake: { semiMajorAxisAu: 45.79, eccentricity: 0.16, inclination: 29.0, longitudeOfAscendingNode: 79.6, argumentOfPeriapsis: 296, periodDays: 111756, meanAnomalyAtEpoch: 165 },
  eris: { semiMajorAxisAu: 67.78, eccentricity: 0.44, inclination: 44.0, longitudeOfAscendingNode: 35.9, argumentOfPeriapsis: 151, periodDays: 203600, meanAnomalyAtEpoch: 205 }
};

const textureSet = texture => texture ? {
  albedo: texture,
  normal: texture.replace('.jpg', '_normal.jpg'),
  roughness: texture.replace('.jpg', '_roughness.jpg'),
  displacement: texture.replace('.jpg', '_displacement.jpg')
} : null;

export const SOLAR_EPOCH = 'J2000 educational approximation';
export const objects = baseObjects.map(item => ({
  ...item,
  elements: orbitalElements[item.id] || null,
  textureSet: textureSet(item.texture),
  lod: item.radius ? [
    { distance: 38, segments: 24, texture: item.texture },
    { distance: 16, segments: 80, texture: item.texture },
    { distance: 0, segments: 160, texture: item.texture }
  ] : []
}));

export const dockOrder = ['sun', 'mercury', 'venus', 'earth', 'mars', 'jupiter', 'saturn', 'uranus', 'neptune', 'pluto'];
export const filters = ['همه', ...new Set(objects.map(item => item.type))];
export const textureBase = 'https://www.solarsystemscope.com/textures/download/';
